CREATE TABLE IF NOT EXISTS `Marca` (
  `id` SMALLINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS `Vendedor` (
  `id` SMALLINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS `Producto` (
  `id` MEDIUMINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `stock` SMALLINT UNSIGNED NOT NULL,
  `marca_id` SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS `Orden` (
  `id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'Order date',
  `producto_id` MEDIUMINT UNSIGNED NOT NULL,
  `vendedor_id` SMALLINT UNSIGNED NOT NULL
);

ALTER TABLE `Producto` ADD FOREIGN KEY (`marca_id`) REFERENCES `Marca` (`id`) ON DELETE CASCADE;

ALTER TABLE `Orden` ADD FOREIGN KEY (`producto_id`) REFERENCES `Producto` (`id`) ON DELETE CASCADE;

ALTER TABLE `Orden` ADD FOREIGN KEY (`vendedor_id`) REFERENCES `Vendedor` (`id`) ON DELETE CASCADE;
